

name: cypressgoitnauka@1.0.0

on: push

jobs:
  cypress-run:
    runs-on: Windows 10 Pro
    steps:
      - name: Checkout
        uses:  actions/checkout@v3

     
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run
          start: npm start

    
 

